### ISSUE TITLE
the topics are poorly shown.

### ISSUE THREAD

**Issue by fretchen** [synqs/synqs.github.io#17]
Visualization of the poor rendering on firefox.
<img width="860" alt="image" src="https://user-images.githubusercontent.com/8323674/122873612-44bd1500-d332-11eb-82d7-73cb31091dde.png">

Is this also what you observed @abraemer ?

**Comment by abraemer** [comment]
Yes exactly. I think something broke in the library (isotope) that does these fluid arrangements. Maybe you can do an update?

**Comment by abraemer** [comment]
Closed by #18
